name: landandexpand
favicon: null
layout_spectrum: 0.10809158463962376
typography_spectrum: 0.0020434525795280933
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.11371149378828704
  lightness: 0.7959187971428037
  saturation: 0.7626718326937407
  rhythmicContrast: 0.3957108298782259
purpose: []
