name: landandexpand
favicon: null
layout_spectrum: 0.10809158463962376
typography_spectrum: 0.0020434525795280933
title: Land and Expand Blog
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ede8ee'
    - '#1c1b21'
    - '#716e75'
    - '#a1a3b2'
    - '#7c4024'
  brandStrength: 0.75
  lightness: 0.75
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
