name: landandexpand
favicon: null
layout_spectrum: 0.10809158463962376
typography_spectrum: 0.0020434525795280933
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#141218'
    - '#fae9d5'
    - '#45463d'
    - '#d3bfa9'
    - '#a4a19c'
  brandStrength: 0.75
  lightness: 0.6875
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
