name: Land And Expand Blog
favicon: null
layout_spectrum: 0.25009
typography_spectrum: 0.57444
title: Land and Expand Blog
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ede8ee'
    - '#1c1b21'
    - '#716e75'
    - '#a1a3b2'
    - '#7c4024'
  brandStrength: 0.8125
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
